all: ../ebin/lthrift.beam ../ebin/lthrift_ets.beam ../ebin/lthrift_process_lb.beam ../ebin/poolManager.beam ../ebin/rop_thrift.beam ../ebin/thrift_worker.beam  ../ebin/thrift_base64_transport.beam ../ebin/thrift_binary_protocol.beam ../ebin/thrift_buffered_transport.beam ../ebin/thrift_client_util.beam ../ebin/thrift_client.beam ../ebin/thrift_disk_log_transport.beam ../ebin/thrift_file_transport.beam ../ebin/thrift_framed_transport.beam ../ebin/thrift_http_transport.beam ../ebin/thrift_json_parser.beam ../ebin/thrift_json_protocol.beam ../ebin/thrift_memory_buffer.beam ../ebin/thrift_processor.beam ../ebin/thrift_protocol.beam ../ebin/thrift_reconnecting_client.beam ../ebin/thrift_server.beam ../ebin/thrift_service.beam ../ebin/thrift_socket_server.beam ../ebin/thrift_socket_transport.beam ../ebin/thrift_transport_state_test.beam  ../ebin/thrift_transport.beam 
  

../ebin/lthrift.beam : lthrift.erl
	erlc -o ../ebin lthrift.erl

../ebin/lthrift_ets.beam : lthrift_ets.erl
	erlc -o ../ebin lthrift_ets.erl

../ebin/lthrift_process_lb.beam : lthrift_process_lb.erl
	erlc -o ../ebin lthrift_process_lb.erl

../ebin/poolManager.beam : poolManager.erl
	erlc -o ../ebin poolManager.erl

../ebin/rop_thrift.beam : rop_thrift.erl
	erlc -o ../ebin rop_thrift.erl

../ebin/thrift_worker.beam : thrift_worker.erl
	erlc -o ../ebin thrift_worker.erl
	
../ebin/thrift_base64_transport.beam : thrift_base64_transport.erl
	erlc -o ../ebin thrift_base64_transport.erl
	
../ebin/thrift_binary_protocol.beam : thrift_binary_protocol.erl
	erlc -o ../ebin thrift_binary_protocol.erl
	
../ebin/thrift_buffered_transport.beam : thrift_buffered_transport.erl
	erlc -o ../ebin thrift_buffered_transport.erl
	
../ebin/thrift_client_util.beam : thrift_client_util.erl
	erlc -o ../ebin thrift_client_util.erl
	
../ebin/thrift_client.beam : thrift_client.erl
	erlc -o ../ebin thrift_client.erl
	
../ebin/thrift_disk_log_transport.beam : thrift_disk_log_transport.erl
	erlc -o ../ebin thrift_disk_log_transport.erl
	
../ebin/thrift_file_transport.beam : thrift_file_transport.erl
	erlc -o ../ebin thrift_file_transport.erl
	
../ebin/thrift_framed_transport.beam : thrift_framed_transport.erl
	erlc -o ../ebin thrift_framed_transport.erl
	
../ebin/thrift_http_transport.beam : thrift_http_transport.erl
	erlc -o ../ebin thrift_http_transport.erl
	
../ebin/thrift_json_parser.beam : thrift_json_parser.erl
	erlc -o ../ebin thrift_json_parser.erl
	
../ebin/thrift_json_protocol.beam : thrift_json_protocol.erl
	erlc -o ../ebin thrift_json_protocol.erl
	
../ebin/thrift_memory_buffer.beam : thrift_memory_buffer.erl
	erlc -o ../ebin thrift_memory_buffer.erl
	
../ebin/thrift_processor.beam : thrift_processor.erl
	erlc -o ../ebin thrift_processor.erl
	
../ebin/thrift_protocol.beam : thrift_protocol.erl
	erlc -o ../ebin thrift_protocol.erl
	
../ebin/thrift_reconnecting_client.beam : thrift_reconnecting_client.erl
	erlc -o ../ebin thrift_reconnecting_client.erl
	
../ebin/thrift_server.beam : thrift_server.erl
	erlc -o ../ebin thrift_server.erl
	
../ebin/thrift_service.beam : thrift_service.erl
	erlc -o ../ebin thrift_service.erl
	
../ebin/thrift_socket_server.beam : thrift_socket_server.erl
	erlc -o ../ebin thrift_socket_server.erl
	
../ebin/thrift_socket_transport.beam : thrift_socket_transport.erl
	erlc -o ../ebin thrift_socket_transport.erl
	
../ebin/thrift_transport_state_test.beam : thrift_transport_state_test.erl
	erlc -o ../ebin thrift_transport_state_test.erl
	
../ebin/thrift_transport.beam : thrift_transport.erl
	erlc -o ../ebin thrift_transport.erl
	

	




clean: rm -rf ../ebin/*.beam
